{% set version = "0.7.2" %}

package:
  name: cartes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cartes/cartes-{{ version }}.tar.gz
  sha256: 1429b858a5c5d99a1699454bb2395096749e5be69bf96440863847d34c88b472

build:
  noarch: python
  entry_points:
    - cartes = cartes.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry >=1.0.10
    - poetry-core
  run:
    - python >=3.8,<3.11
    - numpy >=1.21,<2.0
    - matplotlib-base >=3.5,<4.0
    - scipy >=1.7,<2.0
    - pandas >=1.3,<2.0
    - geopandas >=0.10
    - altair >=4.2,<5.0
    - requests >=2.27,<3.0
    - Shapely >=1.8,<2.0
    - aiohttp >=3.8.1,<4.0
    - appdirs >=1.4.4,<1.5
    - importlib_metadata >=4.2,<5.0
    - lxml >=4.7,<5.0
    - tqdm >=4.62,<5.0
    - Cartopy >=0.19
    - pyproj >=3.1
    - jsonschema >=3.0,<4.0
    - beautifulsoup4 >=4.10,<5

test:
  requires:
    - pytest
    - pip
  commands:
    - pip check
  imports:
    - cartes

about:
  home: https://github.com/xoolive/cartes
  license: MIT
  license_file: license.txt
  summary: Facilities to produce meaningful maps
  doc_url: https://cartes-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
