{% set version = "0.8.2" %}

package:
  name: cartes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cartes/cartes-{{ version }}.tar.gz
  sha256: 404bf6f314a67fe0b163452e8122b863cc87e4ebc7e811087b40f8ccf4b216d7

build:
  noarch: python
  entry_points:
    - cartes = cartes.tiles.fastapi:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9,<4.0

    - altair >=5.4.1
    - appdirs >=1.4.4
    - beautifulsoup4 >=4.12.3
    - fastapi >=0.115.0
    - geopandas >=1.0.1
    - httpx[http2] >=0.27.2
    - jsonschema >=4.23.0
    - lxml >=5.3.0
    - matplotlib-base >=3.9.2
    - nest-asyncio >=1.6.0
    - pandas >=2.2.3
    - shapely >=2.0.6
    - tqdm >=4.66.5
    - uvicorn >=0.31.0

    - cartopy >=0.23.0
    - numpy >=2.0.2
    - pyproj >=3.7.0
    - scipy >=1.13.1

test:
  requires:
    - pytest
    - pip
  commands:
    - pip check
  imports:
    - cartes

about:
  home: https://github.com/xoolive/cartes
  license: MIT
  license_file: license.txt
  summary: Facilities to produce meaningful maps
  doc_url: https://cartes-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
