{% set version = "0.4" %}

package:
  name: cartes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cartes/cartes-{{ version }}.tar.gz
  sha256: fa59fed12d143e4bd40790361a46c30cc773b61bb8d89ba1e40f2372fec24c45

build:
  noarch: python
  entry_points:
    - cartes = cartes.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - scipy
    - matplotlib-base
    - pandas >=1.0.0
    - pyproj >=3.0
    - Cartopy
    - Shapely
    - requests
    - appdirs
    - tqdm >=4.28
    - geopandas
    - importlib_metadata

test:
  requires:
    - pytest
    - pip
  commands:
    - pip check
  imports:
    - cartes

about:
  home: https://github.com/xoolive/cartes
  license: MIT
  license_file: license.txt
  summary: Facilities to produce meaningful maps
  doc_url: https://cartes-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
