{% set version = "0.8.5" %}
{% set python_min = "3.10" %}

package:
  name: cartes
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cartes/cartes-{{ version }}.tar.gz
  sha256: 52fc2cd27b42c27579a72741f2cbbfcb248b423ab116f6f91042ca5aab680836

build:
  noarch: python
  entry_points:
    - cartes = cartes.tiles.fastapi:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - altair >=5.4.1
    - appdirs >=1.4.4
    - beautifulsoup4 >=4.12.3
    - fastapi >=0.120.1
    - geopandas >=1.1.1
    - httpx[http2] >=0.27.2
    - jsonschema >=4.25.1
    - lxml >=6.0.2
    - matplotlib-base >=3.10.7
    - nest-asyncio >=1.6.0
    - pandas >=2.3.3
    - shapely >=2.1.2
    - tqdm >=4.66.5
    - uvicorn >=0.38.0
    - cartopy >=0.25.0
    - numpy >=2.1.2
    - pyproj >=3.7.0
    - scipy >=1.14.1

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pip
  commands:
    - pip check
  imports:
    - cartes

about:
  home: https://github.com/xoolive/cartes
  license: MIT
  license_file: license.txt
  summary: Facilities to produce meaningful maps
  doc_url: https://cartes-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive

